theme: jekyll-theme-midnight
title: Welcome to Dragohnz's homepage!
description: This is the start of my coding career, feel free to bookmark this to keep an eye on my projects.
code review: Here is my first ever personal [code review](https://youtu.be/OFC6ghUbXUc)
